# Generated by Django 3.1.2 on 2020-10-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20201022_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='Brief',
            field=models.TextField(default='test default'),
            preserve_default=False,
        ),
    ]
