# Generated by Django 3.1.2 on 2020-10-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_recipes_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediants_model',
            name='IngrediantsPerson',
            field=models.IntegerField(default=1, max_length=5),
        ),
    ]
