# Generated by Django 3.1.2 on 2020-10-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20201023_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediants_model',
            name='IngrediantsPerson',
        ),
        migrations.AddField(
            model_name='recipes',
            name='IngrediantsPerson',
            field=models.IntegerField(default=1),
        ),
    ]
