# Generated by Django 3.1.2 on 2020-10-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_auto_20201023_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='Brief',
            field=models.TextField(blank=True, null=True),
        ),
    ]
