# Generated by Django 3.1.2 on 2020-11-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_auto_20201023_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='catogories',
            field=models.CharField(default='others', max_length=200),
        ),
    ]
